# Combined Deployment and Service manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
    spec:
      imagePullSecrets:  # Add this section for the secret
        - name: regcred  # Reference the Secret you created
      containers:
        - name: nginx
          image: 603321723110.dkr.ecr.ap-south-1.amazonaws.com/nginx:nginx-cp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: cp-container
          image: 603321723110.dkr.ecr.ap-south-1.amazonaws.com/zupain-cp:CP_BUILD_NO
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: services
          image: 603321723110.dkr.ecr.ap-south-1.amazonaws.com/zupain-services:SERVICES_BUILD_NO
          imagePullPolicy: Always
          env:
          - name: START_CMD
            value: "start"
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
spec:
  selector:
    app: SERVICE_NAME
  ports:
    - port: 80
      targetPort: 80
  type: NodePort