import { Col, Row } from 'antd';
import React from 'react';
import './policy.less';

const PrivacyPolicy = () => {
  return (
    <>
      <div className="pt-20 bg-white ">
        <div className="text-center">
          <h2 className="fs-20 fw-600">ZUPAIN TECH PRIVATE LIMITED</h2>
          <h2 className="fs-20 fw-600">PRIVACY POLICY</h2>
        </div>
        <br />
        <Row>
          <Col
            xs={{ span: 20, offset: 2 }}
            sm={{ span: 20, offset: 2 }}
            md={{ span: 14, offset: 5 }}
            lg={{ span: 14, offset: 5 }}
            xl={{ span: 14, offset: 5 }}
          >
            <p>
              Zupain Tech Private Limited, a company incorporated under
              Companies Act, 2013 having its registered office situated at, Door
              No. H2B, Ground floor, Bharathidasan Colony, K.K Nagar, Chennai,
              TN 600078 (hereinafter “Zupain”/ “We”/ “Us”/ “Our”) is a SAAS
              platform engaged in the business of providing white label
              solutions to its Users (defined hereinafter) who are businesses,
              enabling them to build an online store to sell their products
              (“Services”). [Peritum1]{' '}
            </p>
            <br />
            <p>
              This privacy policy (“Privacy Policy”) details the manner in which
              We collect, Use, share, disclose and protect the Personal
              Information (defined hereinafter) provided by the Users and
              visitors (jointly and severally referred to as “You” or “User” in
              this Privacy Policy) of Our website bearing the domain name{' '}
              <a href="https://www.dev-admin.zupain.com">
                www.dev-admin.zupain.com
              </a>{' '}
              or our web application (“Platform”).
            </p>
            <br />
            <p>
              THIS PRIVACY POLICY IS AN ELECTRONIC RECORD IN ACCORDANCE WITH THE
              INFORMATION TECHNOLOGY ACT, 2000 AND THE RULES FRAMED THEREUNDER.
              THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES
              NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES. THIS PRIVACY
              POLICY IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3
              (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES)
              RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS,
              PRIVACY POLICY AND TERMS OF USE FOR ACCESS OR USAGE OF THIS
              PLATFORM.
            </p>
            <br />
            <p>
              BY USING THIS PLATFORM OR BY OTHERWISE GIVING US YOUR PERSONAL
              INFORMATION, YOU WILL BE HEREBY DEEMED TO HAVE READ, UNDERSTOOD
              AND AGREED TO THE PRACTICES AND POLICIES OUTLINED IN THIS PRIVACY
              POLICY AND AGREE TO BE BOUND BY THIS PRIVACY POLICY HEREIN.
            </p>
            <br />
            <p>
              IN THE EVENT THAT YOU ARE LOCATED IN THE EUROPEAN UNION (“EU”)
              AND/OR EUROPEAN ECONOMIC AREA (“EEA”), YOU WILL BE ASKED TO
              PROVIDE CLEAR AND AFFIRMATIVE CONSENT TO THE COLLECTION,
              PROCESSING, AND SHARING OF YOUR PERSONAL INFORMATION, SUBJECT TO
              WITHDRAWAL OF YOUR CONSENT AT ANY TIME, ON REQUEST.
            </p>
            <br />
            <p>
              ZUPAIN WILL NOT SHARE ANY PERSONAL INFORMATION WITH ANY THIRD
              PARTY EXCEPT AS OUTLINED IN THIS PRIVACY POLICY OR AS PERMITTED BY
              ANY APPLICABLE LAW. THIS PRIVACY POLICY IS IN COMPLIANCE WITH THE
              INFORMATION TECHNOLOGY ACT 2000, THE INFORMATION TECHNOLOGY
              (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE
              PERSONAL DATA OR INFORMATION) RULES 2011, REGULATION (EU) 2016/679
              OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL OF 27 APRIL 2016 ON
              THE PROTECTION OF NATURAL PERSONS WITH REGARD TO THE PROCESSING OF
              PERSONAL DATA AND ON THE FREE MOVEMENT OF SUCH DATA (HEREINAFTER
              REFERRED TO AS THE “GENERAL DATA PROTECTION REGULATION” OR “GDPR”)
              AS AND WHERE APPLICABLE AND ANY OTHER APPLICABLE LAWS WITH RESPECT
              TO PLATFORM IN COLLECTION AND/OR PROCESSING OF PERSONAL
              INFORMATION (AS DEFINED HEREINAFTER) OF USERS, AND TO PROVIDE
              APPROPRIATE PROTECTION AND CARE WITH RESPECT TO THE TREATMENT OF
              SUCH INFORMATION IN ACCORDANCE WITH APPLICABLE LAWS.
            </p>
            <br />
            <p>
              YOU HEREBY CONSENT TO OUR COLLECTION, USE AND SHARING, AND
              DISCLOSURE OF YOUR INFORMATION AS DESCRIBED IN THIS PRIVACY
              POLICY. WE HERERBY RESERVE THE RIGHT TO (WITHOUT LIMITATION)
              CHANGE, MODIFY, ADD AND/OR DELETE PORTIONS OF THE TERMS OF THIS
              PRIVACY POLICY, AT OUR SOLE DISCRETION, AT ANY TIME. IF YOU DO NOT
              AGREE WITH THE TERMS OF THIS PRIVACY POLICY AT ANY TIME, DO NOT
              ACCESS OUR PLATFORM. IF YOU VISIT THE PLATFORM ON BEHALF OF
              SOMEONE ELSE (SUCH YOUR CHILD) AND/OR ANY OTHER ENTITY (SUCH AS
              YOUR EMPLOYER), YOU REPRESENT THAT YOU ARE AUTHORISED BY SUCH
              INDIVIDUAL AND/OR ENTITY TO: (I) ACCEPT THIS PRIVACY POLICY ON
              SUCH INDIVIDUAL’S AND/OR ENTITY’S BEHALF; AND (II) CONSENT ON
              BEHALF OF SUCH INDIVIDUAL AND/OR ENTITY TO OUR COLLECTION, USE AND
              DISCLOSURE OF SUCH INDIVIDUAL’S AND/OR ENTITY’S PERSONAL
              INFORMATION AS DESCRIBED IN THIS PRIVACY POLICY.
            </p>
            <br />
            <p>
              THE PRIVACY POLICY FOR ACCESS AND USE OF OUR PLATFORM IS AS
              FOLLOWS:
            </p>
            <ul>
              <li>
                <h4>1. COLLECTION OF PERSONAL INFORMATION</h4>
              </li>
              <li>
                <p>
                  1.1. When You access Our Platform, You may provide Us with
                  Your Personal Information, including when You register an
                  account with Us or sign up to receive announcements or other
                  information from Us. Such information may be inclusive of but
                  not limited to: (a) Details of your business/commercial
                  entity, such as but not limited to its registered name,
                  details of incorporation, registered office address, etc as
                  notified by Us from time to time; (b) Contact Details such as
                  email address and contact number; (c) Login ID and password;
                  (d) Your usage details such as time, frequency, duration and
                  pattern of use, features used and any other information that
                  is willingly shared by You; and (e) Financial and payment
                  information when You make purchases.
                </p>
              </li>
              <li>
                <p>
                  1.2. In addition to the above, the following information is
                  defined as “Personal Information” as is defined under
                  Information Technology (Reasonable Security Practices &
                  Procedures and Sensitive Personal Data or Information) Rules,
                  2011 (“SPDI Rules”) to mean any information that relates to a
                  natural person, which, either directly or indirectly, in
                  combination with other information available or likely to be
                  available with a body corporate, is capable of identifying
                  such person.
                </p>
              </li>
              <li>
                <p>
                  1.3. The SPDI Rules further define “Sensitive Personal Data or
                  Information” of a person to mean personal information about
                  that person relating to the following: (i) passwords; (ii)
                  financial information such as bank accounts, credit and debit
                  card details or other payment instrument details; (vii)
                  information received by body corporate under lawful contract
                  or otherwise; (viii) visitor details as provided at the time
                  of registration or thereafter; and (ix) call data records
                  These points and the Points in Clauses 1.1 and 1.2 shall
                  collectively referred to as “Personal Information”
                  hereinafter.
                </p>
              </li>
              <li>
                <p>
                  1.4. We may also obtain information about You from other
                  sources and We may add and maintain such information along
                  with the information about You obtained through the Platform.
                </p>
              </li>
              <li>
                <p>
                  1.5. To improve the responsiveness of the Platform, as You
                  navigate through the Platform, We collect Your computer
                  operating system type, browser type, browser language, the
                  websites You visited previously, pages You viewed, time spent
                  on each page, access times and information about Your use and
                  actions on Our site. Certain other information is also
                  passively collected (that is, gathered without Your actively
                  providing the information) Using various technologies and
                  means, such as but not limited to internet protocol addresses,
                  cookies, internet tags, and navigational data collection.
                  Navigational data is used for system management, to improve
                  the content of the site, market research purposes, and to
                  communicate information to visitors. Cookies are small data
                  files stored on Your hard drive by a website. We may Use both
                  session cookies (which expire once You close Your web browser)
                  and persistent cookies (which stay on Your computer until You
                  delete them) to provide You with a more personal and
                  interactive experience when using the website. This type of
                  information is collected to make the Platform more useful to
                  You and to tailor the experience with Us to meet Your
                  interests and needs.
                </p>
              </li>
              <li>
                <p>
                  1.6. You are responsible for maintaining the accuracy of the
                  information You submit to Us, such as Your contact
                  information. If You provide any information that is untrue,
                  inaccurate, out of date or incomplete (or becomes untrue,
                  inaccurate, out of date or incomplete), or if Zupain has
                  reasonable grounds to suspect that the information provided by
                  You is untrue, inaccurate, out of date or incomplete, Zupain
                  shall disregard and delete such at its sole discretion, and
                  may bar/restrict You from Using or accessing its Platform in
                  the future. Zupain shall retain the right not to correct,
                  delete or update Your Personal Information, including (a)
                  where the Personal Information is opinion data that is kept
                  solely for evaluative purpose; and (b) the Personal
                  Information is in documents related to a prosecution if all
                  proceedings relating to the prosecution have not been
                  completed.
                </p>
              </li>
              <li>
                <h4>2. CONSENT TO USE PERSONAL INFORMATION</h4>
              </li>
              <li>
                <p>
                  2.1. By providing Your Personal Information and / or accessing
                  the site, You are consenting to the collection, storage, use
                  and disclosure of Your Personal Information by Zupain to
                  operate, maintain, and improve the Platform and the services
                  offered by it, to process and deliver contest entries and
                  rewards, to respond to comments and questions and to provide
                  customer service, to send information including confirmations,
                  invoices, technical notices, updates, security alerts and
                  support and administrative messages, to communicate about
                  promotions, upcoming events and other news about products and
                  services offered by Us and Our selected partners, to link or
                  combine User information with other personal information, to
                  protect, investigate and deter against fraudulent,
                  unauthorized, or illegal activity, or to provide the products
                  or services that You request.
                </p>
              </li>
              <li>
                <p>
                  2.2. Collection of information which has been designated as
                  ‘sensitive personal data or information’ under the SPDI Rules
                  requires Your express consent and by affirming Your assent to
                  this Privacy Policy, You provide Your consent to such
                  collection as required under applicable law. As outlined in
                  this Privacy Policy, We will not process Your Personal
                  Information without a lawful basis to do so. In general, We
                  may process Your Personal Information on the legal basis of:
                  (i) consent (ii) contract (if You have either availed services
                  and/or entered into an agreement with Zupain and such
                  processing is a necessary part thereof); (iii) compliance with
                  Applicable Laws (as set forth below); (iv) to protect the
                  vital interests of any individual.
                </p>
              </li>
              <li>
                <p>
                  2.3. In the event that You are a User from EU or EEA, then You
                  will be asked to provide clear and affirmative consent to the
                  collection, processing, and sharing of Your Personal
                  Information by/with Zupain, subject to withdrawal of Your
                  consent at any time on request. Under GDPR, EU/EEA residents
                  have the following rights: (a) To know the purpose to process
                  the Personal Information; (b) To know the status of Personal
                  Information processed; (c) Access the Personal Information
                  that is processed; (d) To erase or rectify the Personal
                  Information; (e) Restrict the processing of the Personal
                  Information; (f) Data portability of the Personal Information
                  provided by You. This allows the User to download all Personal
                  Information that has been shared with Zupain in a readable
                  format for Your own purposes; and (g) Opt-out option from
                  processing the Personal Information (unless Zupain has
                  otherwise compelling legitimate grounds) The abovementioned
                  rights can be exercised by EU/EEA residents by contacting
                  Zupain at support@zupain.com
                </p>
              </li>
              <li>
                <h4>
                  3. ACCESS, RETENTION AND DELETION OF PERSONAL INFORMATION
                </h4>
              </li>
              <li>
                <p>
                  3.1. Zupain will take reasonable steps to accurately record
                  the Personal Information that You provide to Zupain and any
                  subsequent updates. As a User, You have the right to access
                  and correct Your Personal Information that Zupain holds.
                </p>
              </li>
              <li>
                <p>
                  3.2. You can follow the “unsubscribe” instructions in
                  commercial email messages. If required by You, Zupain will
                  delete the Personal Information provided by You, but Zupain
                  may retain information about You for the purposes authorized
                  under this Privacy Policy and for the duration as mentioned in
                  this Privacy Policy, unless prohibited by law. Thereafter,
                  Zupain will either delete Your Personal Information or
                  de-identify it so that it is anonymous and not attributed to
                  Your identity. Upon deletion of Your Personal Information,
                  copies of Your Personal Information may remain viewable in
                  cached and archived pages.
                </p>
              </li>
              <li>
                <p>
                  3.3. We shall retain Your Personal Information for a duration
                  of one (1) year unless otherwise agreed to under an agreement
                  between You and Zupain or if We require the Personal
                  Information for a longer duration in order to provide services
                  to You, under a separate agreement.
                </p>
              </li>
              <li>
                <p>
                  3.4. The data protection rights available to You include: the
                  right to access, right to rectification, right to erasure,
                  right to restrict processing, right to object to processing,
                  right to data portability.
                </p>
              </li>
              <li>
                <h4>4. SHARING OF PERSONAL INFORMATION</h4>
              </li>
              <li>
                <h4>
                  4.1. We shall not disclose Your Personal Information to third
                  parties except as mentioned herein: (a) At Your direction to
                  disclose such information; (b) We may share or disclose Your
                  non-private, aggregated or otherwise non-personal information
                  with third parties in compliance with the terms of this
                  Privacy Policy and the applicable laws. (c) Information that
                  We collect from Our Users, including Personal Information, is
                  considered to be a business asset. As a result, if We are
                  acquired as a result of a transaction such as a merger,
                  acquisition or asset sale or if We go out of business or enter
                  bankruptcy, Your Personal Information may be disclosed or
                  transferred to the third-party acquirer in connection with the
                  transaction. (d) We may share or disclose Your Personal
                  Information for legal, protection and safety purposes,
                  including to comply with laws, to respond to lawful requests
                  and legal processes, and to protect the rights and property of
                  Our company, agents, customers and others, which includes
                  enforcing Our agreements, policies, and terms of service. We
                  may share information in an emergency, which includes
                  protecting the safety of Our employees, Our customers, or any
                  other person, however in compliance with applicable laws.
                </h4>
              </li>
              <li>
                <h4>5. CHOICES AND CHANGES</h4>
              </li>
              <li>
                <p>
                  5.1. Our marketing emails tell You how to “opt-out.” If You
                  opt out, We may still send You non-marketing emails.
                  Non-marketing emails include emails about Your accounts and
                  Our business dealings with You. You may send requests about
                  Your Personal Information to Our contact information below.
                  You can request to change contact choices, opt-out of certain
                  information sharing with others, and update Your Personal
                  Information. You can typically remove and reject cookies from
                  Our site with Your browser settings. Many browsers are set to
                  accept cookies until You change Your settings. If You remove
                  or reject Our cookies, it could affect how Our site works for
                  You. You may at any time also intimate to Us that You wish to
                  have Your data erased from Our servers/records. We will in
                  such circumstances comply and within reasonable timeframes
                  have such data removed from Our servers.
                </p>
              </li>
              <li>
                <h4>6. SECURITY AND CONFIDENTIALITY OF PERSONAL INFORMATION</h4>
              </li>
              <li>
                <p>
                  6.1. Zupain takes all necessary precautions to protect Your
                  Personal Information both online and off-line, and implements
                  reasonable security practices and measures including certain
                  managerial, technical, operational and physical security
                  control measures in order to prevent unauthorized access,
                  disclosure or Use of Your Personal Information.
                </p>
              </li>
              <li>
                <p>
                  6.2. Please be aware, however, that these security measures do
                  not guarantee that Your information will not be accessed,
                  compromised, corrupted, disclosed or destroyed. Accordingly,
                  We cannot guarantee the absolute security of any information.
                </p>
              </li>
              <li>
                <p>
                  6.3. By Using the Platform, You acknowledge that You
                  understand and agree to assume these risks. Your Personal
                  Information may be stored on the servers provided to Us by
                  third parties (based on separate agreements containing
                  security related clauses in accordance with applicable laws)
                </p>
              </li>
              <li>
                <p>
                  6.4. Zupain makes all User information accessible to its
                  employees, agents or partners and third parties only on a
                  need-to-know basis, and binds only its employees to strict
                  confidentiality obligations. Zupain shall not rent or sell
                  potentially personally-identifying and personally-identifying
                  information to anyone. Other than to its employees,
                  contractors and affiliated organizations, as described above,
                  Zupain discloses potentially personally-identifying and
                  personally-identifying information only in response to a
                  subpoena, court order or other governmental request, or when
                  Zupain believes in good faith that disclosure is reasonably
                  necessary to protect the property or rights of Zupain, third
                  parties or the public at large.
                </p>
              </li>
              <li>
                <p>
                  6.5. Zupain is not responsible for the confidentiality,
                  security or distribution of Your Personal Information by Our
                  partners and third parties outside the scope of Our agreement
                  with such partners and third parties. Further, Zupain shall
                  not be responsible for any breach of security or for any
                  actions of any third parties or events that are beyond the
                  reasonable control of Zupain including but not limited to,
                  acts of government, computer hacking, unauthorised access to
                  computer data and storage device, computer crashes, breach of
                  security and encryption, poor quality of Internet service or
                  telephone service of the User etc.
                </p>
              </li>
              <li>
                <h4>7. CHILDREN</h4>
              </li>
              <li>
                <p>
                  7.1. We do not knowingly collect Personal Information from
                  children under eighteen (18) years of age. If You become aware
                  that Your child has provided Us with Personal Information
                  without Your consent, please contact Us at hello@zupain.com.
                  If We learn that We have collected Personal Information of a
                  child under eighteen (18) years of age, We will take steps to
                  delete such information from Our records and terminate the
                  child’s account as soon as possible.
                </p>
              </li>
              <li>
                <h4>8. BUSINESS TRANSFERS</h4>
              </li>
              <li>
                <p>
                  8.1. If Zupain, or substantially all of its assets, were
                  acquired, or in the unlikely event that Zupain goes out of
                  business or enters bankruptcy, the acquired Personal
                  Information would be one of the assets that is transferred or
                  acquired by a third party. You acknowledge that such transfers
                  may occur, and that any acquirer of Zupain may continue to Use
                  Your Personal Information as set forth in this Privacy Policy.
                </p>
              </li>
              <li>
                <h4>9. ACCEPTANCE</h4>
              </li>
              <li>
                <p>
                  9.1. Your acceptance of this Privacy Policy is effected by
                  Your usage of the Platform. Should You have any concerns with
                  using Our Platform, kindly contact Us at the email ID provided
                  above and immediately cease using the Platform.
                </p>
              </li>
            </ul>
          </Col>
        </Row>
      </div>
    </>
  );
};

export default PrivacyPolicy;
